### ISSUE TITLE
Can use other particle form third

### ISSUE THREAD

**Issue by natsupy** [ljackso/ParticlesInAnOverlayCanvas#1]
i using your particle, it working fine, but when using other, it not view in camera, so can you help to fix it
it look like that, thank you so much !
https://youtu.be/yA1FKIWNJpA

**Comment by ljackso** [comment]
Hey, so  one simple problem might just be checking the z pos of your particle system is actually infront of the camera, but it's a little difficult to tell from your video what else could be the issue. If you'd like to send me over the project I'm happy to take a look and see if I can figure it out! I can't think of any reason why other particle systems wouldn't work with the current camera set up.

**Comment by natsupy** [comment]
thank you, i can fix this, change some shader of material in renderer and can view them in camera, from Particles/Additive to Mobile/Particles/Additive and it work!

**Comment by ljackso** [comment]
Awesome glad you were able to sort it out!
